### ISSUE TITLE
Unable to download the Opentelemetry-metric-go package.

### ISSUE THREAD

**Issue by mohan5v5988** [dynatrace-oss/opentelemetry-metric-go#8]
I tried to download the metric-go package into my app, and when I did go get package, I got the following error.
steps followed 
1. Tried to get the package with **`go get github.com/dynatrace-oss/opentelemetry-metric-go/dynatrace`**
2. then got an error saying that **`cannot find module providing package go.opentelemetry.io/otel/api/metric`**
3. I tried to get the package manually with **`go get go.opentelemetry.io/otel/api/metric`** but it says **`does not contain package go.opentelemetry.io/otel/api/metric`** 
4. I think we need to update the module in the **`dynatrace.go`** file.

Please suggest any solution.

I have added the log.

```bash 
❯ go get github.com/dynatrace-oss/opentelemetry-metric-go/dynatrace
go: downloading github.com/dynatrace-oss/opentelemetry-metric-go v0.1.0-beta
go: downloading go.opentelemetry.io/otel/sdk/export/metric v0.26.0
go: downloading go.opentelemetry.io v0.1.0
go: downloading go.opentelemetry.io/otel/metric v0.26.0
github.com/dynatrace-oss/opentelemetry-metric-go/dynatrace imports
        go.opentelemetry.io/otel/api/metric: cannot find module providing package go.opentelemetry.io/otel/api/metric
github.com/dynatrace-oss/opentelemetry-metric-go/dynatrace imports
        go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
❯ go get go.opentelemetry.io/otel/api/metric
go get: module go.opentelemetry.io/otel@upgrade found (v1.3.0), but does not contain package go.opentelemetry.io/otel/api/metric```

**Comment by dyladan** [comment]
hmm I'm not seeing this error when i am working in an empty clean directory

https://asciinema.org/a/g4ULM9dQZalKdk2FCxM0reVOH

Can you include the go.mod and go.sum file you're using?

**Comment by mohan5v5988** [comment]
HI I can't share my go files. You are correct when I do empty clean directory I don't see this problem. Thanks for the help.

**Comment by mohan5v5988** [comment]
I was able to fix it by getting the whole package **`go get github.com/dynatrace-oss/opentelemetry-metric-go`**
